Subroutine set_params_BC(pa)

use parameters_site
use parameters_plant
implicit none
real :: pa(58)

! Process parameters 
CLAIV     = pa(1)	   
COCRESMX  =	pa(2)
CSTAVM	  = pa(3)
DAYLB	  =	pa(4)  
DAYLP	  =	pa(5)
DLMXGE	  = pa(6)
FSLAMIN   = pa(7)	 
HAGERE    =	pa(8)	  
K         =	pa(9)  
LAICR	  = pa(10)	 
LAIEFT    = pa(11)	   
LAITIL	  =	pa(12) 
LFWIDG	  =	pa(13)
LFWIDV	  = pa(14) 
NELLVM	  = pa(15)
PHENCR    = pa(16)	 
PHY	      =	pa(17)	  
RDRSCO	  =	pa(18)
RDRSMX	  = pa(19)	 
RDRTEM    = pa(20) 
RGENMX	  =	pa(21)  
ROOTDM	  =	pa(22)	  
RRDMAX	  = pa(23)
RUBISC    = pa(24)	   
SHAPE	  =	pa(25)	  
SIMAX1T	  =	pa(26)
SLAMAX    = pa(27)
TBASE     = pa(28)	   
TCRES     = pa(29)	  
TOPTGE	  =	pa(30)	  
TRANCO	  = pa(31)
YG        = pa(32)

! Winter parameters	 
Dparam	  = pa(33)	
FGAS	  = pa(34)	
FO2MX	  = pa(35)	
gamma	  = pa(36)	
Hparam	  = pa(37)	
KRDRANAER	 = pa(38)	
KRESPHARD	 = pa(39)	
KRSR3H	     = pa(40)	
KRTOTAER	 = pa(41)	
KSNOW	     = pa(42)	
LAMBDAsoil	 = pa(43)	
LDT50A	     = pa(44)	
LDT50B	     = pa(45)	
LT50MN	     = pa(46)	
LT50MX	     = pa(47)	
RATEDMX	     = pa(48)	
reHardRedDay = pa(49)	
RHOnewSnow	 = pa(50)	
RHOpack	     = pa(51)	
SWret	     = pa(52)	
SWrf	     = pa(53)	
THARDMX	     = pa(54)	
TrainSnow	 = pa(55)	
TsurfDiff  	 = pa(56)
	
KLUETILG     = pa(57) 
FRTILGI      = pa(58)

return
end
